version: 1
pythonVersion: 3.11.7

services:
  - type: web
    name: stockscreener-backend
    env: python
    runtime: python-3.11
    buildCommand: |
      set -e
      cd backend
      poetry config virtualenvs.create false
      poetry install --no-dev
    startCommand: |
      cd backend
      poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: POLYGON_API_KEY
        sync: false
    region: frankfurt
    plan: free

  - type: web
    name: stockscreener-frontend
    env: static
    buildCommand: |
      set -e
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://stockscreener-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 