services:
  - type: web
    name: stockscreener-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://stockscreener-frontend.onrender.com

  - type: web
    name: stockscreener-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://stockscreener-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 