services:
  - type: web
    name: stockscreener-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stockscreener-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://stockscreener-frontend.onrender.com

  - type: postgres
    name: stockscreener-db
    region: frankfurt
    plan: free
    databaseName: stockscreener
    user: stockscreener_user
    ipAllowList: []

  - type: static
    name: stockscreener-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://stockscreener-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 