services:
  - type: web
    name: stockscreener-backend
    env: python
    runtime: python-3.11
    buildCommand: |
      cd backend && pip install --upgrade pip && pip install numpy==1.24.3 && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: POLYGON_API_KEY
        sync: false
    region: frankfurt
    plan: free

  - type: web
    name: stockscreener-frontend
    env: static
    buildCommand: |
      cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://stockscreener-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 